== Priorities

Note: The original version of the GBIF Strategic Plan 2017-2021 are presented the five priorities it identified in reverse order. These were subsequently reordered to allow the Implementation Plan to place its focus squarely on the global network of GBIF Participants and data publishers and reflect the need to build on these foundations in order to address GBIF’s informatics, content mobilization, data curation and delivered products.

== . Empower global network

Ensure that governments, researchers and users are equipped and supported to share, improve and use data through the GBIF network, regardless of geography, language or institutional affiliation.

===	Remove barriers to participation

* Engage with government stakeholders in all regions to expand national participation in GBIF
* Ensure that data holders everywhere have access to tools and support to publish and use data through GBIF
* Evaluate and respond to needs for delivery of data and data summaries in additional formats and through new technologies

===	Increase benefits associated with publishing biodiversity data

*	Promote best practices for citation and acknowledgment of data publishers
*	Report on use of data accessed through GBIF network
*	Enable data publishers and users to collaborate in correcting and improving data

===	Address capacity needs

*	Maintain current and complete guidance materials to support all types of data holder and data publisher
*	Support capacity exchange and reuse of tools and expertise to accelerate establishment of national biodiversity information facilities
*	Partner with other organizations, institutions and agencies to maximize benefits from investments in capacity development in all regions
*	Promote inclusion of biodiversity informatics training as part of relevant university and workplace education
*	Seek supplementary funding to support development of national biodiversity information facilities 

== . Enhance biodiversity information infrastructure

Provide leadership, expertise and tools to support the integration of all biodiversity information as an interconnected digital knowledgebase.

=== Coordinate vision and strengthen partnerships with major biodiversity informatics initiatives

*	Deliver comprehensive taxonomic solutions in partnership with Catalogue of Life and other partners
*	Develop and promote shared architecture to enable all biodiversity knowledge to be integrated and managed as a linked digital resource (“biodiversity knowledge graph”)
*	Agree plans and secure funding to implement shared architecture in partnership with other major biodiversity informatics organizations, particularly around taxonomic and nomenclatural data
*	Seek funding with partner initiatives to deliver a stable and efficient network of interoperable infrastructures connecting and maintaining all biodiversity knowledge

=== Promote standardization and common mechanisms for exchange of biodiversity data

*	Promote development and adoption of a comprehensive domain model, standards and vocabularies for biodiversity information through TDWG and other partnerships
*	Provide leadership in development and adoption of standardized tools, data formats and vocabularies to enable mobilization and use of all biodiversity knowledge

=== Provide stable and persistent data infrastructure to support research

*	Implement and promote models and tools for persistent sharing and use of open data, including publishing tools, repositories, data licensing models, persistent identification, citation and tracking tools (the components which form the “Culture” layer in the GBIO document)
*	Contribute to wider initiatives, particularly in the context of the Research Data Alliance, to standardize management and use of open data in research

== . Fill data gaps 

Prioritize and promote mobilization of new data resources that combine with existing resources to maximize the coverage, completeness and resolution of GBIF-mediated data, particularly with respect to taxonomy, geography and time.

===	Expand checklists to cover all taxonomic groups

* Coordinate and deliver comprehensive solutions in partnership with Catalogue of Life and other partners
*	Target mobilization of checklists for remaining taxonomic groups
*	Mobilize national and regional species lists

===	Identify and prioritize gaps in spatial and temporal data

* Develop models and criteria to assess completeness and adequacy of existing data
*	Maintain “gap map” highlighting priority regions, taxa and time periods to fill gaps

=== Engage institutions and researchers with complementary data

*	Develop mechanisms to integrate other classes of data providing information on species occurrence (checklists, expert maps, sample-based data, remote sensing, genomics, etc.)
*	Ensure that tools and documentation support mobilization of data streams from all relevant research areas and observation systems
*	Promote best practices for GBIF Nodes to identify, engage and support all national holders of relevant data
*	Develop mechanisms to support data sharing from researchers and institutions in countries which are not yet GBIF Participants
*	Seek supplementary funding to support large-scale content mobilization

== . Improve data quality

Ensure that all data within the GBIF network are of the highest-possible quality and associated with clear indicators enabling users to assess their origin, relevance and usefulness for any application.

===	Enhance automated data validation

* Validate metadata for completeness and interpretability
*	Validate individual data records
*	Validate data sets as a whole (patterns, etc.)

===	Implement tools for expert curation

*	Integrate and promote tools to annotate individual records and batches of records 
*	Enable publication of cleaned data (“reference data sets”)
*	Improve communication with and support for data publishers to address issues

=== Provide clear quality indicators for all data

* Improve metadata for all data sets explaining methods, provenance, transformations, etc. (“data stories”)
*	Provide metrics and filters for download of data subsets matching user criteria
*	Work with expert communities to develop reference data sets and/or filters for data suitable for key applications

== . Deliver relevant data 

Ensure that GBIF delivers data in the form and completeness required to meet the highest-priority needs of science and, through science, society.

===	Engage with expert communities to manage data to the highest quality possible

* Engage taxonomic societies, professional researchers and amateur experts as partners in assessing and improving GBIF-mediated data
* Define criteria for determining data relevance (elements, completeness, etc.) for key applications and domains
*	Develop mechanisms for community curation of taxonomic, geographic or thematic sectors within GBIF-mediated data

=== Deliver well-organized and validated data to support key applications

* Develop mechanisms to monitor and prioritize data needs from GBIF audiences
*	Support supra-national research, conservation and sustainable use, particularly through CBD, IPBES and GEO BON
*	Provide data relevant to understanding and responding to the impacts of climate change on biodiversity
*	Ensure that GBIF serves as a virtual natural history collection to support taxonomic research
*	Assess and develop role of GBIF in support of Nagoya Protocol
