== Background and Context

=== GBIF progress and challenges

GBIF has a unique position among international organizations working within the field of biodiversity informatics. It is the only body supported by national governments with a mandate for mobilization and management of data on all taxonomic groups. 

Since it was set up in 2001, GBIF’s Participant community has expanded (as of July 2015) to include 54 countries and 39 organizations or economies as signatories to the GBIF Memorandum of Understanding. This global network, supported by a securely established secretariat in Copenhagen, has mobilized more than half a billion data records and serves as a resource for a growing audience that produces a flourishing body of peer-reviewed research and policy applications each year.

Hundreds of institutions have published their valuable data and provided free, worldwide open access to them through the GBIF network. The volume of data and the number of contributing data publishers continues to expand, thanks to collaborative efforts by GBIF community’s Participant nodes to promote best practices, share skills and help overcome barriers to data sharing. In the last 15 years, the GBIF network has played a central role in developing and adopting workable, scalable technologies along with incentives for mobilizing, organizing and accessing very large volumes of biodiversity data. 

GBIF has completed its early development phases and is now an operational infrastructure, recognized as the global aggregator for species occurrence data and as a leader in development of globally connected solutions for biodiversity information. GBIF’s role is recognized in the context of the Convention on Biological Diversity (CBD), Intergovernmental Platform on Biodiversity and Ecosystem Services (IPBES), Group on Earth Observations Biodiversity Information Network (GEO BON) and other international activities to support biodiversity assessment and planning.

GBIF’s achievements to date have been impressive (see Box 1 on progress relating to the 2012-2015 Strategic Plan). However as the network approaches its fourth funding period, from 2017 to 2021, GBIF stakeholders need to address key remaining challenges within a coherent strategy with clearly understood and up-to-date priorities and well-defined goals. This document sets out such a strategy, aimed at putting GBIF on a secure footing and serving the needs of the global community into the next decade.

Among the critical challenges addressed by this Strategic Plan are:

*	*Widening and strengthening participation*: Many countries in all regions remain unconnected with GBIF, and progress toward establishing and strengthening national capacity to mobilize and access relevant data varies significantly among existing participants. Funding remains a challenge, with costs shared among a relatively small number of countries and disproportionate impact when one or more of these is unable to contribute at agreed levels. More conspicuously, data coverage is highly variable between regions and even between adjacent countries.
*	*Building trust in data products*: Improvements are required in the quality and fitness-for-use of aggregated data and metadata within the network. More work is needed to ensure that all data are sufficiently documented and catalogued in ways that assist users in filtering according to their needs, and greater precision and accuracy is necessary particularly in representing taxonomy. Mechanisms and incentives are needed to engage expert communities in validation and correction of this global data resource.
*	*Filling data gaps and broadening the evidence base*: Opportunities exist to make significant advances both in the completeness and coverage of GBIF data and of the richness of available information. GBIF must identify and understand where gaps and biases in existing data make it inadequate to meet user needs and must prioritize effective responses to address these issues. All relevant sources of data must be incorporated, including sample-based data sets, ecogenomics and other molecular research, remote-sensing, literature records, local and regional checklists, and expert knowledge. These resources should be used to establish GBIF not only as a source of occurrence information but also as an effective tool to discover and access data on species abundance and community composition, and related genetic data.
*	*Scaling up infrastructure*: Integrating growing volumes of data will bring new challenges in efficient storage, management, presentation and access of these data. GBIF will face related challenges as it engages with more countries and organizations and as its services become more mission-critical for many stakeholders. During 2017-2021, GBIF must accordingly continue to innovate and to review all processes to ensure smooth future growth. 

=== GBIF’s place in the landscape

Information on the world’s biodiversity is recognized as an essential requirement to support research into species and ecosystems, to underpin conservation and sustainability goals and to support a wide range of spatial assessment and management activity. Delivering information systems to support these needs is a complex requirement, given the multidimensional complexity of biodiversity itself and the limited nature of all direct observations and measurements of biodiversity patterns.

As outlined in the Global Biodiversity Informatics Outlook (GBIO – www.biodiversityinformatics.org), coordinated activity is required across multiple levels of cooperation and thousands of institutions, organizations and researchers. The GBIO presents a multi-tiered model:

*	Adoption of a global approach to free and open sharing of data (CULTURE layer)
*	Broad-scale engagement of data holding institutions to share data in open and compatible formats (DATA layer)
*	Comprehensive services to catalogue and organize these data (EVIDENCE layer)
*	Large-scale modelling activities to provide the best possible picture of actual distributions, community composition and ecosystem structure (UNDERSTANDING layer)

<<<gbio-framework,GBIO Framework>>

The global community has the opportunity to address the challenges of each of these layers in parallel, with increased efficiency and shared benefits from advances in any aspect.

Coordinated activity across these layers will deliver the information tools needed to deliver an effective GEO Biodiversity Observation Network (GEO BON, the biodiversity component within the Global Earth Observation System of Systems (GEOSS)), and thereby offer data products open to community validation in support of the scientific assessments of the Intergovernmental Platform on Biodiversity and Ecosystem Services (IPBES), and addressing the needs of governments and MEAs including the Convention on Biological Diversity (CBD).

GBIF’s mission relates to coordinated global effort in the CULTURE and DATA layers of the GBIO framework and to delivery of key components of the EVIDENCE layer. GBIF aims to deliver the most complete and best-organized integration possible of all data items representing evidence of the occurrence of any species in time and space. In doing so, GBIF can serve both as a global resource for spatial modeling of biodiversity patterns and as a tool for taxonomists, collection managers and others requiring information on and access to the world's natural history collections.
