== Deliver relevant data 

Ensure that GBIF delivers data in the form and completeness required to meet the highest-priority needs of science and, through science, society.

===	Engage with expert communities to manage data to the highest quality possible

* Engage taxonomic societies, professional researchers and amateur experts as partners in assessing and improving GBIF-mediated data
* Define criteria for determining data relevance (elements, completeness, etc.) for key applications and domains
*	Develop mechanisms for community curation of taxonomic, geographic or thematic sectors within GBIF-mediated data

=== Deliver well-organized and validated data to support key applications

* Develop mechanisms to monitor and prioritize data needs from GBIF audiences
*	Support supra-national research, conservation and sustainable use, particularly through CBD, IPBES and GEO BON
*	Provide data relevant to understanding and responding to the impacts of climate change on biodiversity
*	Ensure that GBIF serves as a virtual natural history collection to support taxonomic research
*	Assess and develop role of GBIF in support of Nagoya Protocol
