== Enhance biodiversity information infrastructure

Provide leadership, expertise and tools to support the integration of all biodiversity information as an interconnected digital knowledgebase.

== Coordinate vision and strengthen partnerships with major biodiversity informatics initiatives

*	Deliver comprehensive taxonomic solutions in partnership with Catalogue of Life and other partners
*	Develop and promote shared architecture to enable all biodiversity knowledge to be integrated and managed as a linked digital resource (“biodiversity knowledge graph”)
*	Agree plans and secure funding to implement shared architecture in partnership with other major biodiversity informatics organizations, particularly around taxonomic and nomenclatural data
*	Seek funding with partner initiatives to deliver a stable and efficient network of interoperable infrastructures connecting and maintaining all biodiversity knowledge

== Promote standardization and common mechanisms for exchange of biodiversity data

*	Promote development and adoption of a comprehensive domain model, standards and vocabularies for biodiversity information through TDWG and other partnerships
*	Provide leadership in development and adoption of standardized tools, data formats and vocabularies to enable mobilization and use of all biodiversity knowledge

== Provide stable and persistent data infrastructure to support research

*	Implement and promote models and tools for persistent sharing and use of open data, including publishing tools, repositories, data licensing models, persistent identification, citation and tracking tools (the components which form the “Culture” layer in the GBIO document)
*	Contribute to wider initiatives, particularly in the context of the Research Data Alliance, to standardize management and use of open data in research
