== Improve data quality

Ensure that all data within the GBIF network are of the highest-possible quality and associated with clear indicators enabling users to assess their origin, relevance and usefulness for any application.

===	Enhance automated data validation

* Validate metadata for completeness and interpretability
*	Validate individual data records
*	Validate data sets as a whole (patterns, etc.)

===	Implement tools for expert curation

*	Integrate and promote tools to annotate individual records and batches of records 
*	Enable publication of cleaned data (“reference data sets”)
*	Improve communication with and support for data publishers to address issues

=== Provide clear quality indicators for all data

* Improve metadata for all data sets explaining methods, provenance, transformations, etc. (“data stories”)
*	Provide metrics and filters for download of data subsets matching user criteria
*	Work with expert communities to develop reference data sets and/or filters for data suitable for key applications
