== GBIF’s place in the landscape

Information on the world’s biodiversity is recognized as an essential requirement to support research into species and ecosystems, to underpin conservation and sustainability goals and to support a wide range of spatial assessment and management activity. Delivering information systems to support these needs is a complex requirement, given the multidimensional complexity of biodiversity itself and the limited nature of all direct observations and measurements of biodiversity patterns.

As outlined in the Global Biodiversity Informatics Outlook (GBIO – www.biodiversityinformatics.org), coordinated activity is required across multiple levels of cooperation and thousands of institutions, organizations and researchers. The GBIO presents a multi-tiered model:

*	Adoption of a global approach to free and open sharing of data (CULTURE layer)
*	Broad-scale engagement of data holding institutions to share data in open and compatible formats (DATA layer)
*	Comprehensive services to catalogue and organize these data (EVIDENCE layer)
*	Large-scale modelling activities to provide the best possible picture of actual distributions, community composition and ecosystem structure (UNDERSTANDING layer)

The global community has the opportunity to address the challenges of each of these layers in parallel, with increased efficiency and shared benefits from advances in any aspect.

Coordinated activity across these layers will deliver the information tools needed to deliver an effective GEO Biodiversity Observation Network (GEO BON, the biodiversity component within the Global Earth Observation System of Systems (GEOSS)), and thereby offer data products open to community validation in support of the scientific assessments of the Intergovernmental Platform on Biodiversity and Ecosystem Services (IPBES), and addressing the needs of governments and MEAs including the Convention on Biological Diversity (CBD).

GBIF’s mission relates to coordinated global effort in the CULTURE and DATA layers of the GBIO framework and to delivery of key components of the EVIDENCE layer. GBIF aims to deliver the most complete and best-organized integration possible of all data items representing evidence of the occurrence of any species in time and space. In doing so, GBIF can serve both as a global resource for spatial modeling of biodiversity patterns and as a tool for taxonomists, collection managers and others requiring information on and access to the world's natural history collections.
